API_BASE_URL = '/api/v1'
DEFAULT_PASSWORD = 'Test@123456'
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

ROLE_TEACHER = 1
ROLE_LAB_ADMIN = 2
ROLE_DEPT_ADMIN = 4
ROLE_SUPER_ADMIN = 16
ROLE_SYSTEM_ADMIN = 32

API_ENDPOINTS = {
    'auth': {
        'captcha': 'auth/captcha/',
        'captcha_verify': 'auth/captcha/verify/',
        'login': 'auth/login/',
        'logout': 'auth/logout/',
        'token_refresh': 'auth/token/refresh/',
        'password_change': 'auth/password/change/',
        'password_reset': 'auth/password/reset/',
        'password_batch_reset': 'auth/password/batch-reset/',
        'security_question': 'auth/security-question/',
        'security_question_user': 'auth/security-question/user/',
        'security_question_verify': 'auth/security-question/verify/',
        'password_reset_by_security': 'auth/password/reset-by-security/',
        'password_reset_contact': 'auth/password-reset-contact/',
    },
    'users': {
        'list': 'users/',
        'detail': 'users/{id}/',
        'batch_delete': 'users/batch_delete/',
        'activate': 'users/{id}/activate/',
        'update_role': 'users/{id}/update_role/',
        'assign_permission': 'users/{id}/assign_permission/',
        'cleanup_data': 'users/{id}/cleanup_data/',
        'import_users': 'users/import_users/',
        'options': 'users/options/',
        'profile': 'users/profile/',
    },
    'departments': {
        'list': 'departments/',
        'detail': 'departments/{id}/',
        'batch_delete': 'departments/batch_delete/',
        'options': 'departments/options/',
        'check_conflicts': 'departments/check_conflicts/',
    },
    'laboratories': {
        'list': 'laboratories/',
        'detail': 'laboratories/{id}/',
        'batch_delete': 'laboratories/batch_delete/',
        'check_delete_impact': 'laboratories/check_delete_impact/',
        'admin_options': 'laboratories/admin_options/',
        'options': 'laboratories/options/',
        'summary': 'laboratories/{id}/summary/',
        'all_summary': 'laboratories/all_summary/',
    },
    'equipments': {
        'list': 'equipments/',
        'detail': 'equipments/{id}/',
        'batch_delete': 'equipments/batch_delete/',
        'category_options': 'equipments/category_options/',
        'status_options': 'equipments/status_options/',
    },
    'schedules': {
        'list': 'schedules/',
        'detail': 'schedules/{id}/',
        'batch_delete': 'schedules/batch_delete/',
        'check_conflict': 'schedules/check_conflict/',
        'form_options': 'schedules/form_options/',
        'laboratory_options': 'schedules/laboratory_options/',
        'archive_settings': 'schedules/archive-settings/',
        'manual_cleanup': 'schedules/manual-cleanup/',
        'archive_current': 'schedules/archive-current/',
        'archived': 'schedules/archived/{semester_id}/',
        'check_status': 'schedules/check-status/',
    },
    'semesters': {
        'list': 'semesters/',
        'detail': 'semesters/{id}/',
        'batch_delete': 'semesters/batch_delete/',
        'set_current': 'semesters/{id}/set_current/',
        'unset_current': 'semesters/{id}/unset_current/',
        'archive': 'semesters/{id}/archive/',
        'current': 'semesters/current/',
        'options': 'semesters/options/',
        'archive_overview': 'semesters/archive_overview/',
    },
    'records': {
        'list': 'records/',
        'detail': 'records/{id}/',
        'batch_delete': 'records/batch_delete/',
        'form_options': 'records/form_options/',
    },
    'work_orders': {
        'list': 'work-orders/',
        'detail': 'work-orders/{id}/',
        'batch_delete': 'work-orders/batch_delete/',
        'assign': 'work-orders/{id}/assign/',
        'start_handle': 'work-orders/{id}/start_handle/',
        'complete': 'work-orders/{id}/complete/',
        'close': 'work-orders/{id}/close/',
        'form_options': 'work-orders/form_options/',
        'center': 'work-orders/center/',
        'center_detail': 'work-orders/center/{order_id}/',
        'center_hide': 'work-orders/center/{order_id}/hide/',
    },
    'notifications': {
        'list': 'notifications/',
        'detail': 'notifications/{id}/',
        'mark_read': 'notifications/{id}/mark-read/',
        'mark_all_read': 'notifications/mark-all-read/',
        'delete': 'notifications/{id}/delete/',
        'unread_count': 'notifications/unread-count/',
        'send': 'notifications/send/',
        'broadcast': 'notifications/broadcast/',
    },
    'statistics': {
        'dashboard': 'statistics/dashboard/',
        'teacher': 'statistics/teacher/',
        'lab_admin': 'statistics/laboratory-admin/',
        'super_admin': 'statistics/super-admin/',
        'system_superuser': 'statistics/system-superuser/',
        'user_management': 'statistics/user-management/',
        'lab_resource': 'statistics/lab-resource/',
        'scheduling': 'statistics/scheduling/',
        'personal_teaching': 'statistics/personal-teaching/',
        'comprehensive': 'statistics/comprehensive/',
        'comprehensive_export': 'statistics/comprehensive/export/',
    },
    'ai': {
        'process': 'ai/process/',
        'execute': 'ai/execute/',
        'cancel': 'ai/cancel/',
    },
    'backups': {
        'stats': 'backups/stats/',
        'export': 'backups/export/',
        'info': 'backups/info/',
        'restore': 'backups/restore/',
        'auto_config': 'backups/auto-config/',
        'list': 'backups/list/',
        'download': 'backups/download/{filename}/',
        'delete': 'backups/delete/{filename}/',
    },
    'cache_config': {
        'configs': 'cache-config/configs/',
        'config_detail': 'cache-config/configs/{id}/',
        'config_all': 'cache-config/configs/all/',
        'stats': 'cache-config/stats/',
        'stats_today': 'cache-config/stats/today/',
        'stats_range': 'cache-config/stats/range/',
        'stats_ranking': 'cache-config/stats/ranking/',
        'logs': 'cache-config/logs/',
        'clear': 'cache-config/clear/',
        'overview': 'cache-config/overview/',
        'auto_discover': 'cache-config/auto-discover/',
        'batch_toggle': 'cache-config/batch-toggle/',
    },
    'operation_logs': {
        'list': 'operation-logs/',
        'detail': 'operation-logs/{id}/',
        'stats': 'operation-logs/stats/',
        'recent': 'operation-logs/recent/',
        'modules': 'operation-logs/modules/',
        'export': 'operation-logs/export/',
        'cleanup': 'operation-logs/cleanup/',
    },
    'common': {
        'search': 'common/search/',
        'progress': 'common/progress/',
        'health': 'common/health/',
        'export_laboratories': 'common/export/laboratories/',
        'export_schedules': 'common/export/schedules/',
        'export_records': 'common/export/records/',
        'export_work_orders': 'common/export/work-orders/',
        'export_equipment': 'common/export/equipment/',
        'export_users': 'common/export/users/',
        'export_statistics': 'common/export/statistics/',
        'import_laboratories': 'common/import/laboratories/',
        'import_schedules': 'common/import/schedules/',
        'import_equipment': 'common/import/equipment/',
    },
}
