# Generated by Django 4.2.30 on 2026-04-18 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('operator_username', models.CharField(blank=True, default='', help_text='冗余字段，防止用户被删除后无法显示', max_length=150, verbose_name='操作人用户名')),
                ('module', models.CharField(choices=[('user', '用户管理'), ('equipment', '设备管理'), ('schedule', '课表管理'), ('cache_config', '缓存配置'), ('department', '部门管理'), ('laboratory', '实训室管理'), ('backup', '备份管理'), ('system', '系统设置')], db_index=True, max_length=20, verbose_name='模块')),
                ('operation_type', models.CharField(choices=[('user_create', '创建用户'), ('user_delete', '删除用户'), ('user_update', '更新用户'), ('user_role_update', '更新用户权限'), ('user_batch_delete', '批量删除用户'), ('user_import', '导入用户'), ('user_activate', '启用/禁用用户'), ('equipment_create', '添加设备'), ('equipment_delete', '删除设备'), ('equipment_update', '更新设备'), ('equipment_batch_delete', '批量删除设备'), ('schedule_create', '添加课表'), ('schedule_delete', '删除课表'), ('schedule_update', '更新课表'), ('cache_config_create', '创建缓存配置'), ('cache_config_delete', '删除缓存配置'), ('cache_config_update', '更新缓存配置'), ('cache_clear', '清除缓存'), ('department_create', '创建部门'), ('department_update', '更新部门'), ('department_delete', '删除部门'), ('laboratory_create', '创建实训室'), ('laboratory_update', '更新实训室'), ('laboratory_delete', '删除实训室'), ('backup_create', '创建备份'), ('backup_delete', '删除备份'), ('backup_restore', '恢复备份'), ('system_setting_update', '更新系统设置')], db_index=True, max_length=30, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, default='', help_text='如: User, Equipment, Schedule', max_length=50, verbose_name='目标对象类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标对象ID')),
                ('target_name', models.CharField(blank=True, default='', help_text='便于阅读的名称描述', max_length=200, verbose_name='目标对象名称')),
                ('description', models.TextField(blank=True, default='', help_text='自然语言描述，如: 张三添加了用户李四', verbose_name='操作描述')),
                ('detail', models.JSONField(blank=True, help_text='记录修改前后的值等详细信息', null=True, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='用户代理')),
                ('request_id', models.CharField(blank=True, default='', help_text='关联请求，便于追踪完整请求链路', max_length=50, verbose_name='请求ID')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '系统操作日志',
                'verbose_name_plural': '系统操作日志',
                'db_table': 'system_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'operation_type'], name='system_oper_module_cfc3e1_idx'), models.Index(fields=['operator', 'created_at'], name='system_oper_operato_b03608_idx'), models.Index(fields=['target_type', 'target_id'], name='system_oper_target__d032da_idx'), models.Index(fields=['-created_at'], name='system_oper_created_240ca7_idx')],
            },
        ),
    ]
