# Generated by Django 4.2.30 on 2026-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemoperationlog',
            name='module',
            field=models.CharField(choices=[('user', '用户管理'), ('equipment', '设备管理'), ('schedule', '课表管理'), ('department', '部门管理'), ('laboratory', '实训室管理'), ('backup', '备份管理'), ('system', '系统设置')], db_index=True, max_length=20, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='systemoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('user_create', '创建用户'), ('user_delete', '删除用户'), ('user_update', '更新用户'), ('user_role_update', '更新用户权限'), ('user_batch_delete', '批量删除用户'), ('user_import', '导入用户'), ('user_activate', '启用/禁用用户'), ('equipment_create', '添加设备'), ('equipment_delete', '删除设备'), ('equipment_update', '更新设备'), ('equipment_batch_delete', '批量删除设备'), ('schedule_create', '添加课表'), ('schedule_delete', '删除课表'), ('schedule_update', '更新课表'), ('department_create', '创建部门'), ('department_update', '更新部门'), ('department_delete', '删除部门'), ('laboratory_create', '创建实训室'), ('laboratory_update', '更新实训室'), ('laboratory_delete', '删除实训室'), ('backup_create', '创建备份'), ('backup_delete', '删除备份'), ('backup_restore', '恢复备份'), ('system_setting_update', '更新系统设置')], db_index=True, max_length=30, verbose_name='操作类型'),
        ),
    ]
