FROM node:22-alpine AS build-stage

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=4096"

ARG VITE_PASSWORD_ENCRYPT_KEY
ENV VITE_PASSWORD_ENCRYPT_KEY=${VITE_PASSWORD_ENCRYPT_KEY}

ARG VITE_API_V2_BASE_URL
ENV VITE_API_V2_BASE_URL=${VITE_API_V2_BASE_URL}

COPY package.json yarn.lock ./
RUN corepack enable && yarn install

COPY . .

RUN npx vite build --config vite.config.pc.js

FROM alpine:latest AS production

WORKDIR /app

COPY --from=build-stage /app/dist/pc /app/build

EXPOSE 80

VOLUME ["/app/dist"]

CMD ["sh", "-c", "cp -r /app/build/* /app/dist/ && tail -f /dev/null"]
