# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('usage_date', models.DateField(verbose_name='使用日期')),
                ('time_slot', models.CharField(default='1-4', max_length=20, verbose_name='节次')),
                ('class_hours', models.IntegerField(default=4, verbose_name='学时')),
                ('class_name', models.CharField(blank=True, default='', max_length=100, verbose_name='上课班级')),
                ('student_count', models.IntegerField(default=0, verbose_name='学生人数')),
                ('content', models.TextField(blank=True, default='', verbose_name='实训内容')),
                ('device_status', models.CharField(default='正常', max_length=50, verbose_name='设备状态')),
                ('laboratory_status', models.CharField(default='正常', max_length=50, verbose_name='实训室状态')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '使用记录',
                'verbose_name_plural': '使用记录',
                'db_table': 'usage_records',
                'ordering': ['-usage_date', 'laboratory__code'],
            },
        ),
    ]
