# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratories', '0002_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='laboratories.laboratory', verbose_name='实训室'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='schedules.semester', verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL, verbose_name='教师'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['laboratory', 'usage_date'], name='usage_recor_laborat_18c856_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['teacher', 'usage_date'], name='usage_recor_teacher_671bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['semester', 'usage_date'], name='usage_recor_semeste_af997f_idx'),
        ),
    ]
