# Generated by Django 4.2.30 on 2026-04-08 10:55

import apps.core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, verbose_name='设备编号')),
                ('category', models.CharField(default='计算机', max_length=50, verbose_name='设备类别')),
                ('brand', models.CharField(blank=True, default='', max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='序列号')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='位置')),
                ('cpu', models.CharField(blank=True, default='', max_length=100, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, default='', max_length=50, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='', max_length=50, verbose_name='硬盘')),
                ('gpu', models.CharField(blank=True, default='', max_length=100, verbose_name='显卡')),
                ('os', models.CharField(blank=True, default='', max_length=50, verbose_name='操作系统')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('warranty_expire', models.DateField(blank=True, null=True, verbose_name='保修到期')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('supplier', models.CharField(blank=True, default='', max_length=100, verbose_name='供应商')),
                ('status', models.CharField(choices=[('NORMAL', 'NORMAL'), ('MAINTENANCE', 'MAINTENANCE'), ('DAMAGED', 'DAMAGED'), ('SCRAPPED', 'SCRAPPED'), ('BORROWED', 'BORROWED')], default=apps.core.constants.EquipmentStatus['NORMAL'], max_length=20, verbose_name='状态')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='最后维护日期')),
                ('total_usage_hours', models.IntegerField(default=0, verbose_name='累计使用时长(小时)')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'equipments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='实训室名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='实训室编号')),
                ('building', models.CharField(blank=True, default='', max_length=100, verbose_name='所在楼宇')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='所在楼层')),
                ('room_number', models.CharField(blank=True, default='', max_length=50, verbose_name='房间号')),
                ('capacity', models.IntegerField(default=30, verbose_name='工位数')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='面积(平方米)')),
                ('laboratory_type', models.CharField(default='普通实训室', max_length=50, verbose_name='实训室类型')),
                ('status', models.IntegerField(choices=[(1, 'AVAILABLE'), (2, 'IN_USE'), (3, 'MAINTENANCE'), (4, 'UNAVAILABLE')], default=apps.core.constants.LaboratoryStatus['AVAILABLE'], verbose_name='状态')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('facilities', models.JSONField(blank=True, default=dict, verbose_name='设施配置')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
            ],
            options={
                'verbose_name': '实训室',
                'verbose_name_plural': '实训室',
                'db_table': 'laboratories',
                'ordering': ['code'],
            },
        ),
    ]
