# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_laboratories', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratories', to='users.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='laboratories.laboratory', verbose_name='所属实训室'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['code'], name='laboratorie_code_d16963_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['department', 'status'], name='laboratorie_departm_8a3271_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['admin', 'status'], name='laboratorie_admin_i_4840a8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['code'], name='equipments_code_5b9b85_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['laboratory', 'status'], name='equipments_laborat_30eb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'status'], name='equipments_categor_3150de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('code', 'laboratory')},
        ),
    ]
