# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('course_code', models.CharField(blank=True, default='', max_length=50, verbose_name='课程代码')),
                ('weekday', models.IntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY'), (7, 'SUNDAY')], verbose_name='星期')),
                ('time_slot', models.CharField(help_text='如: 1-2, 3-4, 1,2,3', max_length=20, verbose_name='节次')),
                ('weeks', models.CharField(default='1-18', help_text='如: 1-18, 1,3,5,7-15', max_length=50, verbose_name='上课周次')),
                ('teacher_name', models.CharField(blank=True, default='', help_text='冗余字段', max_length=50, verbose_name='教师姓名')),
                ('class_name', models.CharField(blank=True, default='', max_length=100, verbose_name='上课班级')),
                ('student_count', models.IntegerField(default=0, verbose_name='学生人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '课表',
                'verbose_name_plural': '课表',
                'db_table': 'schedules',
                'ordering': ['laboratory__code', 'weekday', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='学期名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='学期代码')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前学期')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
                ('total_weeks', models.IntegerField(default=18, verbose_name='总周数')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
                'db_table': 'semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TermArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('archive_type', models.CharField(choices=[('lab_info', '实训室信息'), ('device_info', '设备信息'), ('user_info', '用户信息')], max_length=20, verbose_name='归档类型')),
                ('content', models.JSONField(verbose_name='归档内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='归档时间')),
            ],
            options={
                'verbose_name': '学期归档',
                'verbose_name_plural': '学期归档',
                'db_table': 'term_archive',
                'ordering': ['-created_at'],
            },
        ),
    ]
