# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('laboratories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termarchive',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='termarchive',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='schedules.semester', verbose_name='关联学期'),
        ),
        migrations.AddField(
            model_name='semester',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='laboratories.laboratory', verbose_name='实训室'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.semester', verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL, verbose_name='任课教师'),
        ),
        migrations.AlterUniqueTogether(
            name='termarchive',
            unique_together={('semester', 'archive_type')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['laboratory', 'semester', 'weekday'], name='schedules_laborat_507472_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher', 'semester'], name='schedules_teacher_6ffdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['semester', 'is_active'], name='schedules_semeste_a4f2c7_idx'),
        ),
    ]
