# Generated by Django 4.2.30 on 2026-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termarchive',
            name='archive_type',
            field=models.CharField(choices=[('lab_info', '实训室信息'), ('device_info', '设备信息'), ('user_info', '用户信息'), ('usage_records', '使用记录'), ('schedules', '课表记录'), ('work_orders', '工单记录')], max_length=20, verbose_name='归档类型'),
        ),
    ]
