# Generated by Django 4.2.30 on 2026-04-14 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, db_table='department_managers', related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门管理员'),
        ),
    ]
