# Generated by Django 4.2.30 on 2026-04-08 10:55

import apps.core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('maintenance_type', models.IntegerField(choices=[(1, 'ROUTINE'), (2, 'SAFETY'), (3, 'REPAIR'), (4, 'UPGRADE')], default=apps.core.constants.MaintenanceType['REPAIR'], verbose_name='维护类型')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('CLOSED', 'CLOSED')], default=apps.core.constants.WorkOrderStatus['PENDING'], max_length=20, verbose_name='工单状态')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('solution', models.TextField(blank=True, default='', verbose_name='解决方案')),
                ('handle_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='评价')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='反馈')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'work_orders',
                'ordering': ['-reported_at'],
            },
        ),
    ]
