# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
        ('laboratories', '0002_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='laboratories.equipment', verbose_name='关联设备'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='laboratories.laboratory', verbose_name='实训室'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_orders', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='schedules.semester', verbose_name='学期'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['laboratory', 'status'], name='work_orders_laborat_bd1357_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='work_orders_status_d07f78_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['reporter', 'status'], name='work_orders_reporte_0e005f_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['handler', 'status'], name='work_orders_handler_77f949_idx'),
        ),
    ]
