# Generated by Django 4.2.30 on 2026-04-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_add_maintenance_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratories', '0002_initial'),
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='工单编号')),
                ('order_type', models.CharField(choices=[('W', '维护'), ('G', '故障')], default='W', max_length=1, verbose_name='工单类型')),
                ('content', models.TextField(verbose_name='维护内容')),
                ('status', models.CharField(choices=[('maintained', '已维护'), ('pending', '待维护'), ('processing', '维护中')], default='maintained', max_length=20, verbose_name='状态')),
                ('maintenance_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='维护时间')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='laboratories.laboratory', verbose_name='实训实验室')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_records', to=settings.AUTH_USER_MODEL, verbose_name='维护人')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='schedules.semester', verbose_name='学期')),
            ],
            options={
                'verbose_name': '维护记录',
                'verbose_name_plural': '维护记录',
                'db_table': 'maintenance_records',
                'ordering': ['-maintenance_time'],
                'indexes': [models.Index(fields=['laboratory', 'status'], name='maintenance_laborat_8bcdf0_idx'), models.Index(fields=['order_type', 'status'], name='maintenance_order_t_6e99f8_idx'), models.Index(fields=['maintainer', 'status'], name='maintenance_maintai_ebc3a0_idx')],
            },
        ),
    ]
