# Generated by Django 4.2.30 on 2026-04-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='工单编号'),
        ),
    ]
