# Generated by Django 4.2.30 on 2026-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_workorder_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hidden_in_center',
            field=models.BooleanField(default=False, verbose_name='在工单中心隐藏'),
        ),
    ]
