# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('SYSTEM', '系统通知'), ('MAINTENANCE', '维护通知'), ('SCHEDULE', '课表通知'), ('ALERT', '告警通知'), ('INFO', '信息通知')], default='SYSTEM', max_length=20, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('NORMAL', '普通'), ('HIGH', '高'), ('URGENT', '紧急')], default='NORMAL', max_length=10, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_recipient',
            },
        ),
    ]
