# Generated by Django 4.2.30 on 2026-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('period', models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='备份周期')),
                ('last_backup_time', models.DateTimeField(blank=True, null=True, verbose_name='上次备份时间')),
                ('next_backup_time', models.DateTimeField(blank=True, null=True, verbose_name='下次备份时间')),
            ],
            options={
                'verbose_name': '自动备份配置',
                'verbose_name_plural': '自动备份配置',
                'db_table': 'auto_backup_config',
            },
        ),
    ]
