# Generated by Django 4.2.30 on 2026-04-18 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('operation_type', models.CharField(choices=[('config_create', '创建配置'), ('config_update', '更新配置'), ('config_delete', '删除配置'), ('cache_clear', '清除缓存'), ('cache_clear_all', '清除所有缓存'), ('cache_warmup', '缓存预热')], max_length=20, verbose_name='操作类型')),
                ('api_path', models.CharField(blank=True, max_length=200, verbose_name='API路径')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='修改前的值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='修改后的值')),
                ('reason', models.TextField(blank=True, verbose_name='操作原因')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='操作IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='用户代理')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cache_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '缓存操作日志',
                'verbose_name_plural': '缓存操作日志',
                'db_table': 'cache_operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CacheConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('api_path', models.CharField(max_length=200, unique=True, verbose_name='API路径')),
                ('frontend_ttl', models.IntegerField(default=60, verbose_name='前端缓存时间(秒)')),
                ('backend_ttl', models.IntegerField(default=300, verbose_name='后端缓存时间(秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用缓存')),
                ('description', models.TextField(blank=True, verbose_name='配置说明')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cache_configs', to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '缓存配置',
                'verbose_name_plural': '缓存配置',
                'db_table': 'cache_config',
                'ordering': ['api_path'],
            },
        ),
        migrations.CreateModel(
            name='ApiStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('api_path', models.CharField(max_length=200, verbose_name='API路径')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('request_count', models.IntegerField(default=0, verbose_name='请求次数')),
                ('cache_hit_count', models.IntegerField(default=0, verbose_name='缓存命中次数')),
                ('total_response_time', models.FloatField(default=0, verbose_name='总响应时间(ms)')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
            ],
            options={
                'verbose_name': 'API统计',
                'verbose_name_plural': 'API统计',
                'db_table': 'api_stats',
                'ordering': ['-date', 'api_path'],
                'unique_together': {('api_path', 'date')},
            },
        ),
    ]
