# Generated by Django 4.2.30 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheconfig',
            name='category',
            field=models.CharField(choices=[
                ('schedules', '日程管理'),
                ('laboratories', '实训室管理'),
                ('equipments', '设备管理'),
                ('records', '使用记录'),
                ('work_orders', '工单管理'),
                ('users', '用户管理'),
                ('departments', '部门管理'),
                ('semesters', '学期管理'),
                ('notifications', '通知管理'),
                ('ai', 'AI助手'),
                ('backups', '数据备份'),
                ('statistics', '统计分析'),
                ('common', '公共功能'),
                ('other', '其他'),
            ], default='other', max_length=50, verbose_name='功能分类'),
        ),
        migrations.RemoveField(
            model_name='cacheconfig',
            name='frontend_ttl',
        ),
        migrations.AlterModelOptions(
            name='cacheconfig',
            options={'ordering': ['category', 'api_path'], 'verbose_name': '缓存配置', 'verbose_name_plural': '缓存配置', 'db_table': 'cache_config'},
        ),
    ]
