# Generated by Django 4.2.30 on 2026-04-27

from django.db import migrations


def update_category_from_api_path(apps, schema_editor):
    """根据API路径自动更新现有数据的分类"""
    CacheConfig = apps.get_model('cache_config', 'CacheConfig')
    
    CATEGORY_MAPPING = {
        '/schedules/': 'schedules',
        '/laboratories/': 'laboratories',
        '/equipments/': 'equipments',
        '/records/': 'records',
        '/work-orders/': 'work_orders',
        '/users/': 'users',
        '/departments/': 'departments',
        '/semesters/': 'semesters',
        '/notifications/': 'notifications',
        '/ai/': 'ai',
        '/backups/': 'backups',
        '/statistics/': 'statistics',
        '/common/': 'common',
    }
    
    configs = CacheConfig.objects.all()
    updated_count = 0
    
    for config in configs:
        if config.category and config.category != 'other':
            continue
            
        new_category = 'other'
        for path_pattern, category in CATEGORY_MAPPING.items():
            if path_pattern in config.api_path:
                new_category = category
                break
        
        if config.category != new_category:
            config.category = new_category
            config.save(update_fields=['category'])
            updated_count += 1
    
    print(f"Updated {updated_count} cache config categories")


class Migration(migrations.Migration):

    dependencies = [
        ('cache_config', '0002_alter_cacheconfig_options_add_cacheconfig_category_and_more'),
    ]

    operations = [
        migrations.RunPython(update_category_from_api_path),
    ]
